image: node:20-alpine

# Define stages for the pipeline
stages:
  - test

# Cache dependencies to speed up builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# Job for running tests and uploading coverage
variables:
  NEXT_TELEMETRY_DISABLED: "1"   # keep CI quiet

test-and-upload-coverage:
  stage: test
  script:
    # 0 — Install curl
    - apk add --no-cache curl
    
    # 1 — Install & test
    - npm ci
    - npm run test:coverage -- --maxWorkers=2

    # 2 — Download Codecov uploader (bash uploader is deprecated)
    - curl -Os https://cli.codecov.io/v10.4.0/alpine/codecov
    - chmod +x codecov

    # 3 — Upload the LCOV report
    - ./codecov upload-process -f coverage/lcov.info --service gitlab
  artifacts:
    paths:
      - coverage/                     # lets you download the HTML report
    expire_in: 1 week
